import os
import streamlit as st
from dotenv import load_dotenv
from elevenlabs.client import ElevenLabs

# Load environment variables
load_dotenv()

st.set_page_config(page_title="ElevenLabs TTS", page_icon="🎙️", layout="centered")

st.title("🎙️ ElevenLabs Text-to-Speech")
st.markdown("Convert your text into highly realistic speech using the ElevenLabs API.")

# API Key Handling (from .env or user input)
api_key = os.getenv("ELEVENLABS_API_KEY")
if not api_key or api_key == "your_elevenlabs_api_key_here":
    api_key = st.sidebar.text_input("Enter ElevenLabs API Key", type="password")
    if not api_key:
        st.warning("Please enter your ElevenLabs API Key in the sidebar (or add it to your `.env` file) to continue.")
        st.stop()

# Initialize Client
try:
    client = ElevenLabs(api_key=api_key)
except Exception as e:
    st.error(f"Error initializing client: {e}")
    st.stop()

# Sidebar settings
st.sidebar.header("Settings")

# Fetch voices dynamically
@st.cache_data(show_spinner=False)
def get_voices(_client_key):
    # Using the key just for cache invalidation if it changes, 
    # but instantiating a new client locally for the cached function to avoid unhashable type issues.
    temp_client = ElevenLabs(api_key=_client_key)
    try:
        response = temp_client.voices.get_all()
        return {v.name: v.voice_id for v in response.voices}
    except Exception as e:
        return {"Rachel (Fallback)": "21m00Tcm4TlvDq8ikWAM", "Clyde (Fallback)": "2EiwWnXFnvU5JabPnv8n"}

voice_dict = get_voices(api_key)
voice_names = list(voice_dict.keys())

# Let user pick Voice and Model
default_index = 0
for i, name in enumerate(voice_names):
    if "Rachel" in name:
        default_index = i
        break

selected_voice_name = st.sidebar.selectbox("Select Voice", voice_names, index=default_index)
selected_model = st.sidebar.selectbox("Select Model", [
    "eleven_multilingual_v2", 
    "eleven_monolingual_v1", 
    "eleven_turbo_v2"
], index=0)

# Main UI
text_input = st.text_area("Enter text to convert to speech:", height=200, placeholder="Hello! I am an AI voice generated by ElevenLabs.")

if st.button("Generate Audio", type="primary", use_container_width=True):
    if not text_input.strip():
        st.error("Please enter some text.")
    else:
        with st.spinner(f"Generating speech using voice '{selected_voice_name}'..."):
            try:
                voice_id = voice_dict[selected_voice_name]
                audio_generator = client.text_to_speech.convert(
                    text=text_input,
                    voice_id=voice_id,
                    model_id=selected_model,
                    output_format="mp3_44100_128"
                )
                
                # Read generator into bytes
                audio_bytes = b"".join(list(audio_generator))
                
                st.success("Audio generated successfully!")
                
                # Play audio in browser
                st.audio(audio_bytes, format="audio/mp3")
                
                # Allow downloading the file
                st.download_button(
                    label="Download MP3",
                    data=audio_bytes,
                    file_name="generated_audio.mp3",
                    mime="audio/mp3",
                    use_container_width=True
                )
            except Exception as e:
                st.error(f"An error occurred: {e}")
